# Generated by Django 4.2.2 on 2023-07-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_rename_shedule_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
