# Generated by Django 4.2.2 on 2023-07-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0002_alter_myuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='myuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='myuser_permissions', to='auth.permission'),
        ),
    ]
