# Generated by Django 4.2.2 on 2023-07-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentification', '0003_alter_myuser_groups_alter_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='myuser_permissions', to='auth.permission'),
        ),
    ]
